// <auto-generated />
using EnglishApplication.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnglishApplication.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DefaultDataContext))]
    [Migration("20240412130521_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RefreshTokenId")
                        .HasColumnType("integer");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.LearnedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuessedTimes")
                        .HasColumnType("integer");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.HasIndex("WordId");

                    b.ToTable("LearnedWords", (string)null);
                });

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("UserInfos", (string)null);
                });

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Words", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Translation = "слово",
                            Value = "word"
                        },
                        new
                        {
                            Id = 2,
                            Translation = "дом",
                            Value = "house"
                        },
                        new
                        {
                            Id = 3,
                            Translation = "кот",
                            Value = "cat"
                        },
                        new
                        {
                            Id = 4,
                            Translation = "собака",
                            Value = "dog"
                        },
                        new
                        {
                            Id = 5,
                            Translation = "дерево",
                            Value = "tree"
                        },
                        new
                        {
                            Id = 6,
                            Translation = "книга",
                            Value = "book"
                        },
                        new
                        {
                            Id = 7,
                            Translation = "компьютер",
                            Value = "computer"
                        },
                        new
                        {
                            Id = 8,
                            Translation = "небо",
                            Value = "sky"
                        },
                        new
                        {
                            Id = 9,
                            Translation = "солнце",
                            Value = "sun"
                        },
                        new
                        {
                            Id = 10,
                            Translation = "луна",
                            Value = "moon"
                        },
                        new
                        {
                            Id = 11,
                            Translation = "яблоко",
                            Value = "apple"
                        },
                        new
                        {
                            Id = 12,
                            Translation = "банан",
                            Value = "banana"
                        },
                        new
                        {
                            Id = 13,
                            Translation = "машина",
                            Value = "car"
                        },
                        new
                        {
                            Id = 14,
                            Translation = "стол",
                            Value = "table"
                        },
                        new
                        {
                            Id = 15,
                            Translation = "стул",
                            Value = "chair"
                        },
                        new
                        {
                            Id = 16,
                            Translation = "ручка",
                            Value = "pen"
                        },
                        new
                        {
                            Id = 17,
                            Translation = "карандаш",
                            Value = "pencil"
                        },
                        new
                        {
                            Id = 18,
                            Translation = "окно",
                            Value = "window"
                        },
                        new
                        {
                            Id = 19,
                            Translation = "дверь",
                            Value = "door"
                        },
                        new
                        {
                            Id = 20,
                            Translation = "телефон",
                            Value = "phone"
                        },
                        new
                        {
                            Id = 21,
                            Translation = "планшет",
                            Value = "tablet"
                        },
                        new
                        {
                            Id = 22,
                            Translation = "стул",
                            Value = "chair"
                        },
                        new
                        {
                            Id = 23,
                            Translation = "лампа",
                            Value = "lamp"
                        },
                        new
                        {
                            Id = 24,
                            Translation = "часы",
                            Value = "clock"
                        },
                        new
                        {
                            Id = 25,
                            Translation = "книжная полка",
                            Value = "bookshelf"
                        },
                        new
                        {
                            Id = 26,
                            Translation = "кровать",
                            Value = "bed"
                        },
                        new
                        {
                            Id = 27,
                            Translation = "окно",
                            Value = "window"
                        },
                        new
                        {
                            Id = 28,
                            Translation = "чашка",
                            Value = "cup"
                        },
                        new
                        {
                            Id = 29,
                            Translation = "ложка",
                            Value = "spoon"
                        },
                        new
                        {
                            Id = 30,
                            Translation = "вилка",
                            Value = "fork"
                        },
                        new
                        {
                            Id = 31,
                            Translation = "нож",
                            Value = "knife"
                        },
                        new
                        {
                            Id = 32,
                            Translation = "тарелка",
                            Value = "plate"
                        },
                        new
                        {
                            Id = 33,
                            Translation = "телевизор",
                            Value = "television"
                        },
                        new
                        {
                            Id = 34,
                            Translation = "пульт",
                            Value = "remote"
                        },
                        new
                        {
                            Id = 35,
                            Translation = "наушники",
                            Value = "headphones"
                        },
                        new
                        {
                            Id = 36,
                            Translation = "гитара",
                            Value = "guitar"
                        },
                        new
                        {
                            Id = 37,
                            Translation = "микрофон",
                            Value = "microphone"
                        },
                        new
                        {
                            Id = 38,
                            Translation = "колонка",
                            Value = "speaker"
                        },
                        new
                        {
                            Id = 39,
                            Translation = "клавиатура",
                            Value = "keyboard"
                        },
                        new
                        {
                            Id = 40,
                            Translation = "мышь",
                            Value = "mouse"
                        },
                        new
                        {
                            Id = 41,
                            Translation = "скатерть",
                            Value = "tablecloth"
                        },
                        new
                        {
                            Id = 42,
                            Translation = "салфетка",
                            Value = "napkin"
                        },
                        new
                        {
                            Id = 43,
                            Translation = "тарелка",
                            Value = "plate"
                        },
                        new
                        {
                            Id = 44,
                            Translation = "шкаф",
                            Value = "cupboard"
                        },
                        new
                        {
                            Id = 45,
                            Translation = "зеркало",
                            Value = "mirror"
                        },
                        new
                        {
                            Id = 46,
                            Translation = "полотенце",
                            Value = "towel"
                        },
                        new
                        {
                            Id = 47,
                            Translation = "щетка",
                            Value = "brush"
                        },
                        new
                        {
                            Id = 48,
                            Translation = "зубная паста",
                            Value = "toothpaste"
                        },
                        new
                        {
                            Id = 49,
                            Translation = "шампунь",
                            Value = "shampoo"
                        },
                        new
                        {
                            Id = 50,
                            Translation = "мыло",
                            Value = "soap"
                        },
                        new
                        {
                            Id = 51,
                            Translation = "зубная щетка",
                            Value = "toothbrush"
                        },
                        new
                        {
                            Id = 52,
                            Translation = "бритва",
                            Value = "razor"
                        },
                        new
                        {
                            Id = 53,
                            Translation = "расческа",
                            Value = "comb"
                        },
                        new
                        {
                            Id = 54,
                            Translation = "туалет",
                            Value = "toilet"
                        },
                        new
                        {
                            Id = 55,
                            Translation = "раковина",
                            Value = "sink"
                        },
                        new
                        {
                            Id = 56,
                            Translation = "ванна",
                            Value = "bathtub"
                        },
                        new
                        {
                            Id = 57,
                            Translation = "душ",
                            Value = "shower"
                        },
                        new
                        {
                            Id = 58,
                            Translation = "полотенце",
                            Value = "towel"
                        },
                        new
                        {
                            Id = 59,
                            Translation = "туалетная бумага",
                            Value = "toilet paper"
                        },
                        new
                        {
                            Id = 60,
                            Translation = "мусорное ведро",
                            Value = "trash can"
                        },
                        new
                        {
                            Id = 61,
                            Translation = "холодильник",
                            Value = "fridge"
                        },
                        new
                        {
                            Id = 62,
                            Translation = "морозильник",
                            Value = "freezer"
                        },
                        new
                        {
                            Id = 63,
                            Translation = "духовка",
                            Value = "oven"
                        },
                        new
                        {
                            Id = 64,
                            Translation = "микроволновая печь",
                            Value = "microwave"
                        },
                        new
                        {
                            Id = 65,
                            Translation = "плита",
                            Value = "stove"
                        },
                        new
                        {
                            Id = 66,
                            Translation = "чайник",
                            Value = "kettle"
                        },
                        new
                        {
                            Id = 67,
                            Translation = "кофеварка",
                            Value = "coffeemaker"
                        },
                        new
                        {
                            Id = 68,
                            Translation = "посудомоечная машина",
                            Value = "dishwasher"
                        },
                        new
                        {
                            Id = 69,
                            Translation = "стиральная машина",
                            Value = "washing machine"
                        },
                        new
                        {
                            Id = 70,
                            Translation = "сушилка",
                            Value = "dryer"
                        },
                        new
                        {
                            Id = 71,
                            Translation = "утюг",
                            Value = "iron"
                        },
                        new
                        {
                            Id = 72,
                            Translation = "гладильная доска",
                            Value = "ironing board"
                        },
                        new
                        {
                            Id = 73,
                            Translation = "пылесос",
                            Value = "vacuum cleaner"
                        },
                        new
                        {
                            Id = 74,
                            Translation = "метла",
                            Value = "broom"
                        },
                        new
                        {
                            Id = 75,
                            Translation = "швабра",
                            Value = "mop"
                        },
                        new
                        {
                            Id = 76,
                            Translation = "ведро",
                            Value = "bucket"
                        },
                        new
                        {
                            Id = 77,
                            Translation = "лопата для мусора",
                            Value = "dustpan"
                        },
                        new
                        {
                            Id = 78,
                            Translation = "губка",
                            Value = "sponge"
                        },
                        new
                        {
                            Id = 79,
                            Translation = "моющее средство",
                            Value = "dish soap"
                        },
                        new
                        {
                            Id = 80,
                            Translation = "сушилка для посуды",
                            Value = "dish rack"
                        },
                        new
                        {
                            Id = 81,
                            Translation = "спальня",
                            Value = "bedroom"
                        },
                        new
                        {
                            Id = 82,
                            Translation = "гостиная",
                            Value = "living room"
                        },
                        new
                        {
                            Id = 83,
                            Translation = "кухня",
                            Value = "kitchen"
                        },
                        new
                        {
                            Id = 84,
                            Translation = "ванная комната",
                            Value = "bathroom"
                        },
                        new
                        {
                            Id = 85,
                            Translation = "столовая",
                            Value = "dining room"
                        },
                        new
                        {
                            Id = 86,
                            Translation = "офис",
                            Value = "office"
                        },
                        new
                        {
                            Id = 87,
                            Translation = "гараж",
                            Value = "garage"
                        },
                        new
                        {
                            Id = 88,
                            Translation = "сад",
                            Value = "garden"
                        },
                        new
                        {
                            Id = 89,
                            Translation = "балкон",
                            Value = "balcony"
                        },
                        new
                        {
                            Id = 90,
                            Translation = "крыльцо",
                            Value = "porch"
                        },
                        new
                        {
                            Id = 91,
                            Translation = "двор",
                            Value = "yard"
                        },
                        new
                        {
                            Id = 92,
                            Translation = "улица",
                            Value = "street"
                        },
                        new
                        {
                            Id = 93,
                            Translation = "парк",
                            Value = "park"
                        },
                        new
                        {
                            Id = 94,
                            Translation = "школа",
                            Value = "school"
                        },
                        new
                        {
                            Id = 95,
                            Translation = "больница",
                            Value = "hospital"
                        },
                        new
                        {
                            Id = 96,
                            Translation = "супермаркет",
                            Value = "supermarket"
                        },
                        new
                        {
                            Id = 97,
                            Translation = "банк",
                            Value = "bank"
                        },
                        new
                        {
                            Id = 98,
                            Translation = "почта",
                            Value = "post office"
                        },
                        new
                        {
                            Id = 99,
                            Translation = "библиотека",
                            Value = "library"
                        },
                        new
                        {
                            Id = 100,
                            Translation = "ресторан",
                            Value = "restaurant"
                        });
                });

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.LearnedWord", b =>
                {
                    b.HasOne("EnglishApplication.Domain.Aggregate.UserInfo", "UserInfo")
                        .WithMany("LearnedWords")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishApplication.Domain.Aggregate.Word", "Word")
                        .WithMany("LearnedWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.RefreshToken", b =>
                {
                    b.HasOne("EnglishApplication.Domain.Aggregate.Account", "Account")
                        .WithOne("RefreshToken")
                        .HasForeignKey("EnglishApplication.Domain.Aggregate.RefreshToken", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.UserInfo", b =>
                {
                    b.HasOne("EnglishApplication.Domain.Aggregate.Account", "Account")
                        .WithOne("UserInfo")
                        .HasForeignKey("EnglishApplication.Domain.Aggregate.UserInfo", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.Account", b =>
                {
                    b.Navigation("RefreshToken")
                        .IsRequired();

                    b.Navigation("UserInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.UserInfo", b =>
                {
                    b.Navigation("LearnedWords");
                });

            modelBuilder.Entity("EnglishApplication.Domain.Aggregate.Word", b =>
                {
                    b.Navigation("LearnedWords");
                });
#pragma warning restore 612, 618
        }
    }
}
