// <auto-generated />
using System;
using EnglishApplication.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnglishApplication.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DefaultDataContext))]
    [Migration("20240527115526_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.HasKey("Id");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool?>("Guessed")
                        .HasColumnType("boolean")
                        .HasColumnName("guessed");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnName("word_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("WordId");

                    b.ToTable("round", (string)null);
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<int>("UserInfoId")
                        .HasColumnType("integer")
                        .HasColumnName("user_info_id");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbUserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("user_info", (string)null);
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english");

                    b.Property<string>("Russian")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("russian");

                    b.HasKey("Id");

                    b.ToTable("word", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            English = "word",
                            Russian = "слово"
                        },
                        new
                        {
                            Id = 2,
                            English = "house",
                            Russian = "дом"
                        },
                        new
                        {
                            Id = 3,
                            English = "cat",
                            Russian = "кот"
                        },
                        new
                        {
                            Id = 4,
                            English = "dog",
                            Russian = "собака"
                        },
                        new
                        {
                            Id = 5,
                            English = "tree",
                            Russian = "дерево"
                        },
                        new
                        {
                            Id = 6,
                            English = "book",
                            Russian = "книга"
                        },
                        new
                        {
                            Id = 7,
                            English = "computer",
                            Russian = "компьютер"
                        },
                        new
                        {
                            Id = 8,
                            English = "sky",
                            Russian = "небо"
                        },
                        new
                        {
                            Id = 9,
                            English = "sun",
                            Russian = "солнце"
                        },
                        new
                        {
                            Id = 10,
                            English = "moon",
                            Russian = "луна"
                        },
                        new
                        {
                            Id = 11,
                            English = "apple",
                            Russian = "яблоко"
                        },
                        new
                        {
                            Id = 12,
                            English = "banana",
                            Russian = "банан"
                        },
                        new
                        {
                            Id = 13,
                            English = "car",
                            Russian = "машина"
                        },
                        new
                        {
                            Id = 14,
                            English = "table",
                            Russian = "стол"
                        },
                        new
                        {
                            Id = 15,
                            English = "chair",
                            Russian = "стул"
                        },
                        new
                        {
                            Id = 16,
                            English = "pen",
                            Russian = "ручка"
                        },
                        new
                        {
                            Id = 17,
                            English = "pencil",
                            Russian = "карандаш"
                        },
                        new
                        {
                            Id = 18,
                            English = "window",
                            Russian = "окно"
                        },
                        new
                        {
                            Id = 19,
                            English = "door",
                            Russian = "дверь"
                        },
                        new
                        {
                            Id = 20,
                            English = "phone",
                            Russian = "телефон"
                        },
                        new
                        {
                            Id = 21,
                            English = "tablet",
                            Russian = "планшет"
                        },
                        new
                        {
                            Id = 22,
                            English = "chair",
                            Russian = "стул"
                        },
                        new
                        {
                            Id = 23,
                            English = "lamp",
                            Russian = "лампа"
                        },
                        new
                        {
                            Id = 24,
                            English = "clock",
                            Russian = "часы"
                        },
                        new
                        {
                            Id = 25,
                            English = "bookshelf",
                            Russian = "книжная полка"
                        },
                        new
                        {
                            Id = 26,
                            English = "bed",
                            Russian = "кровать"
                        },
                        new
                        {
                            Id = 27,
                            English = "window",
                            Russian = "окно"
                        },
                        new
                        {
                            Id = 28,
                            English = "cup",
                            Russian = "чашка"
                        },
                        new
                        {
                            Id = 29,
                            English = "spoon",
                            Russian = "ложка"
                        },
                        new
                        {
                            Id = 30,
                            English = "fork",
                            Russian = "вилка"
                        },
                        new
                        {
                            Id = 31,
                            English = "knife",
                            Russian = "нож"
                        },
                        new
                        {
                            Id = 32,
                            English = "plate",
                            Russian = "тарелка"
                        },
                        new
                        {
                            Id = 33,
                            English = "television",
                            Russian = "телевизор"
                        },
                        new
                        {
                            Id = 34,
                            English = "remote",
                            Russian = "пульт"
                        },
                        new
                        {
                            Id = 35,
                            English = "headphones",
                            Russian = "наушники"
                        },
                        new
                        {
                            Id = 36,
                            English = "guitar",
                            Russian = "гитара"
                        },
                        new
                        {
                            Id = 37,
                            English = "microphone",
                            Russian = "микрофон"
                        },
                        new
                        {
                            Id = 38,
                            English = "speaker",
                            Russian = "колонка"
                        },
                        new
                        {
                            Id = 39,
                            English = "keyboard",
                            Russian = "клавиатура"
                        },
                        new
                        {
                            Id = 40,
                            English = "mouse",
                            Russian = "мышь"
                        },
                        new
                        {
                            Id = 41,
                            English = "tablecloth",
                            Russian = "скатерть"
                        },
                        new
                        {
                            Id = 42,
                            English = "napkin",
                            Russian = "салфетка"
                        },
                        new
                        {
                            Id = 43,
                            English = "plate",
                            Russian = "тарелка"
                        },
                        new
                        {
                            Id = 44,
                            English = "cupboard",
                            Russian = "шкаф"
                        },
                        new
                        {
                            Id = 45,
                            English = "mirror",
                            Russian = "зеркало"
                        },
                        new
                        {
                            Id = 46,
                            English = "towel",
                            Russian = "полотенце"
                        },
                        new
                        {
                            Id = 47,
                            English = "brush",
                            Russian = "щетка"
                        },
                        new
                        {
                            Id = 48,
                            English = "toothpaste",
                            Russian = "зубная паста"
                        },
                        new
                        {
                            Id = 49,
                            English = "shampoo",
                            Russian = "шампунь"
                        },
                        new
                        {
                            Id = 50,
                            English = "soap",
                            Russian = "мыло"
                        },
                        new
                        {
                            Id = 51,
                            English = "toothbrush",
                            Russian = "зубная щетка"
                        },
                        new
                        {
                            Id = 52,
                            English = "razor",
                            Russian = "бритва"
                        },
                        new
                        {
                            Id = 53,
                            English = "comb",
                            Russian = "расческа"
                        },
                        new
                        {
                            Id = 54,
                            English = "toilet",
                            Russian = "туалет"
                        },
                        new
                        {
                            Id = 55,
                            English = "sink",
                            Russian = "раковина"
                        },
                        new
                        {
                            Id = 56,
                            English = "bathtub",
                            Russian = "ванна"
                        },
                        new
                        {
                            Id = 57,
                            English = "shower",
                            Russian = "душ"
                        },
                        new
                        {
                            Id = 58,
                            English = "towel",
                            Russian = "полотенце"
                        },
                        new
                        {
                            Id = 59,
                            English = "toilet paper",
                            Russian = "туалетная бумага"
                        },
                        new
                        {
                            Id = 60,
                            English = "trash can",
                            Russian = "мусорное ведро"
                        },
                        new
                        {
                            Id = 61,
                            English = "fridge",
                            Russian = "холодильник"
                        },
                        new
                        {
                            Id = 62,
                            English = "freezer",
                            Russian = "морозильник"
                        },
                        new
                        {
                            Id = 63,
                            English = "oven",
                            Russian = "духовка"
                        },
                        new
                        {
                            Id = 64,
                            English = "microwave",
                            Russian = "микроволновая печь"
                        },
                        new
                        {
                            Id = 65,
                            English = "stove",
                            Russian = "плита"
                        },
                        new
                        {
                            Id = 66,
                            English = "kettle",
                            Russian = "чайник"
                        },
                        new
                        {
                            Id = 67,
                            English = "coffeemaker",
                            Russian = "кофеварка"
                        },
                        new
                        {
                            Id = 68,
                            English = "dishwasher",
                            Russian = "посудомоечная машина"
                        },
                        new
                        {
                            Id = 69,
                            English = "washing machine",
                            Russian = "стиральная машина"
                        },
                        new
                        {
                            Id = 70,
                            English = "dryer",
                            Russian = "сушилка"
                        },
                        new
                        {
                            Id = 71,
                            English = "iron",
                            Russian = "утюг"
                        },
                        new
                        {
                            Id = 72,
                            English = "ironing board",
                            Russian = "гладильная доска"
                        },
                        new
                        {
                            Id = 73,
                            English = "vacuum cleaner",
                            Russian = "пылесос"
                        },
                        new
                        {
                            Id = 74,
                            English = "broom",
                            Russian = "метла"
                        },
                        new
                        {
                            Id = 75,
                            English = "mop",
                            Russian = "швабра"
                        },
                        new
                        {
                            Id = 76,
                            English = "bucket",
                            Russian = "ведро"
                        },
                        new
                        {
                            Id = 77,
                            English = "dustpan",
                            Russian = "лопата для мусора"
                        },
                        new
                        {
                            Id = 78,
                            English = "sponge",
                            Russian = "губка"
                        },
                        new
                        {
                            Id = 79,
                            English = "dish soap",
                            Russian = "моющее средство"
                        },
                        new
                        {
                            Id = 80,
                            English = "dish rack",
                            Russian = "сушилка для посуды"
                        },
                        new
                        {
                            Id = 81,
                            English = "bedroom",
                            Russian = "спальня"
                        },
                        new
                        {
                            Id = 82,
                            English = "living room",
                            Russian = "гостиная"
                        },
                        new
                        {
                            Id = 83,
                            English = "kitchen",
                            Russian = "кухня"
                        },
                        new
                        {
                            Id = 84,
                            English = "bathroom",
                            Russian = "ванная комната"
                        },
                        new
                        {
                            Id = 85,
                            English = "dining room",
                            Russian = "столовая"
                        },
                        new
                        {
                            Id = 86,
                            English = "office",
                            Russian = "офис"
                        },
                        new
                        {
                            Id = 87,
                            English = "garage",
                            Russian = "гараж"
                        },
                        new
                        {
                            Id = 88,
                            English = "garden",
                            Russian = "сад"
                        },
                        new
                        {
                            Id = 89,
                            English = "balcony",
                            Russian = "балкон"
                        },
                        new
                        {
                            Id = 90,
                            English = "porch",
                            Russian = "крыльцо"
                        },
                        new
                        {
                            Id = 91,
                            English = "yard",
                            Russian = "двор"
                        },
                        new
                        {
                            Id = 92,
                            English = "street",
                            Russian = "улица"
                        },
                        new
                        {
                            Id = 93,
                            English = "park",
                            Russian = "парк"
                        },
                        new
                        {
                            Id = 94,
                            English = "school",
                            Russian = "школа"
                        },
                        new
                        {
                            Id = 95,
                            English = "hospital",
                            Russian = "больница"
                        },
                        new
                        {
                            Id = 96,
                            English = "supermarket",
                            Russian = "супермаркет"
                        },
                        new
                        {
                            Id = 97,
                            English = "bank",
                            Russian = "банк"
                        },
                        new
                        {
                            Id = 98,
                            English = "post office",
                            Russian = "почта"
                        },
                        new
                        {
                            Id = 99,
                            English = "library",
                            Russian = "библиотека"
                        },
                        new
                        {
                            Id = 100,
                            English = "restaurant",
                            Russian = "ресторан"
                        });
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbRound", b =>
                {
                    b.HasOne("EnglishApplication.Domain.Entities.DbSession", "Session")
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishApplication.Domain.Entities.DbWord", "Word")
                        .WithMany("Rounds")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbSession", b =>
                {
                    b.HasOne("EnglishApplication.Domain.Entities.DbUserInfo", "UserInfo")
                        .WithMany("Sessions")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbUserInfo", b =>
                {
                    b.HasOne("EnglishApplication.Domain.Entities.DbAccount", "Account")
                        .WithOne("UserInfo")
                        .HasForeignKey("EnglishApplication.Domain.Entities.DbUserInfo", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbAccount", b =>
                {
                    b.Navigation("UserInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbSession", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbUserInfo", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("EnglishApplication.Domain.Entities.DbWord", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
